categories:
  impersonate: ~

settings:
  tx_impersonate.loginRedirectPid:
    label: 'Login Redirect PID'
    description: 'Page ID to redirect after impersonation login'
    category: impersonate
    type: page
    default: 0
